name: Output Context
#https://stackoverflow.com/questions/77161818/workflow-not-showing-up-in-github-actions
#on: workflow_dispatch
on: 
  push:
    branches: ["master"]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: echo " ${{ toJson(github) }}"